<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 7/30/2019
 * Time: 1:56 PM
 */
namespace Modules\Food\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\Food\Models\Food;
use Modules\Food\Models\FoodTerm;
use Modules\Food\Models\FoodTranslation;
use Modules\Core\Models\Attributes;
use Modules\Location\Models\Location;
use Modules\Location\Models\LocationCategory;

class FoodController extends AdminController
{
    protected $food;
    protected $food_translation;
    protected $food_term;
    protected $attributes;
    protected $location;
    private $locationCategoryClass;

    public function __construct(Food $food, FoodTranslation $food_translation, FoodTerm $food_term, Attributes $attributes, Location $location,LocationCategory $locationCategoryClass)
    {
        $this->setActiveMenu(route('food.admin.index'));
        $this->food = $food;
        $this->food_translation = $food_translation;
        $this->food_term = $food_term;
        $this->attributes = $attributes;
        $this->location = $location;
        $this->locationCategoryClass = $locationCategoryClass;
    }

    public function callAction($method, $parameters)
    {
        if (!Food::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $this->checkPermission('food_view');
        $query = $this->food::query();
        $query->orderBy('id', 'desc');
        if (!empty($s = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $s . '%');
            $query->orderBy('title', 'asc');
        }
        if (!empty($is_featured = $request->input('is_featured'))) {
            $query->where('is_featured', 1);
        }
        if (!empty($location_id = $request->query('location_id'))) {
            $query->where('location_id', $location_id);
        }
        if ($this->hasPermission('food_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('author_id', $author);
            }
        } else {
            $query->where('author_id', Auth::id());
        }
        $data = [
            'rows'                => $query->with(['author'])->paginate(20),
            'food_manage_others' => $this->hasPermission('food_manage_others'),
            'breadcrumbs'         => [
                [
                    'name' => __('Foods'),
                    'url'  => route('food.admin.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'          => __("Food Management")
        ];
        return view('Food::admin.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('food_view');
        $query = $this->food::onlyTrashed();
        $query->orderBy('id', 'desc');
        if (!empty($s = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $s . '%');
            $query->orderBy('title', 'asc');
        }
        if ($this->hasPermission('food_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('author_id', $author);
            }
        } else {
            $query->where('author_id', Auth::id());
        }
        $data = [
            'rows'                => $query->with(['author'])->paginate(20),
            'food_manage_others' => $this->hasPermission('food_manage_others'),
            'recovery'            => 1,
            'breadcrumbs'         => [
                [
                    'name' => __('Foods'),
                    'url'  => route('food.admin.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'          => __("Recovery Food Management")
        ];
        return view('Food::admin.index', $data);
    }

    public function create(Request $request)
    {
        $this->checkPermission('food_create');
        $row = new $this->food();
        $row->fill([
            'status' => 'publish'
        ]);
        $data = [
            'row'               => $row,
            'attributes'        => $this->attributes::where('service', 'food')->get(),
            'food_location'    => $this->location::where('status', 'publish')->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'translation'       => new $this->food_translation(),
            'breadcrumbs'       => [
                [
                    'name' => __('Foods'),
                    'url'  => route('food.admin.index')
                ],
                [
                    'name'  => __('Add Food'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Add new Food")
        ];
        return view('Food::admin.detail', $data);
    }

    public function edit(Request $request, $id)
    {
        $this->checkPermission('food_update');
        $row = $this->food::find($id);
        if (empty($row)) {
            return redirect(route('food.admin.index'));
        }
        $translation = $row->translate($request->query('lang',get_main_lang()));
        if (!$this->hasPermission('food_manage_others')) {
            if ($row->author_id != Auth::id()) {
                return redirect(route('food.admin.index'));
            }
        }
        $data = [
            'row'               => $row,
            'translation'       => $translation,
            "selected_terms"    => $row->terms->pluck('term_id'),
            'attributes'        => $this->attributes::where('service', 'food')->get(),
            'food_location'    => $this->location::where('status', 'publish')->get()->toTree(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'enable_multi_lang' => true,
            'breadcrumbs'       => [
                [
                    'name' => __('Foods'),
                    'url'  => route('food.admin.index')
                ],
                [
                    'name'  => __('Edit Food'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Edit: :name", ['name' => $row->title])
        ];
        return view('Food::admin.detail', $data);
    }

    public function store(Request $request, $id)
    {

        if(is_demo_mode()){
            return redirect()->back()->with('danger',__("DEMO MODE: can not add data"));
        }
        if ($id > 0) {
            $this->checkPermission('food_update');
            $row = $this->food::find($id);
            if (empty($row)) {
                return redirect(route('food.admin.index'));
            }
            if ($row->author_id != Auth::id() and !$this->hasPermission('food_manage_others')) {
                return redirect(route('food.admin.index'));
            }
        } else {
            $this->checkPermission('food_create');
            $row = new $this->food();
            $row->status = "publish";
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'status',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'duration',
            'start_time',
            'price',
            'sale_price',
            'ticket_types',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
            'enable_service_fee',
            'service_fee',
            'surrounding',
            'end_time',
            'duration_unit',
        ];
        if ($this->hasPermission('food_manage_others')) {
            $dataKeys[] = 'author_id';
        }
        $row->fillByAttr($dataKeys, $request->input());
        if ($request->input('slug')) {
            $row->slug = $request->input('slug');
        }
        $res = $row->saveOriginOrTranslation($request->input('lang'), true);
        if ($res) {
            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }
            if ($id > 0) {
                event(new UpdatedServiceEvent($row));
                return back()->with('success', __('Food updated'));
            } else {
                event(new CreatedServicesEvent($row));
                return redirect(route('food.admin.edit', $row->id))->with('success', __('Food created'));
            }
        }
    }

    public function saveTerms($row, $request)
    {
        $this->checkPermission('food_manage_attributes');
        if (empty($request->input('terms'))) {
            $this->food_term::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->food_term::firstOrCreate([
                    'term_id'   => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->food_term::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function bulkEdit(Request $request)
    {

        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action) {
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->food::where("id", $id);
                    if (!$this->hasPermission('food_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('food_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->delete();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "permanently_delete":
                foreach ($ids as $id) {
                    $query = $this->food::where("id", $id);
                    if (!$this->hasPermission('food_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('food_delete');
                    }
                    $row = $query->withTrashed()->first();
                    if ($row) {
                        $row->forceDelete();
                    }
                }
                return redirect()->back()->with('success', __('Permanently delete success!'));
                break;
            case "recovery":
                foreach ($ids as $id) {
                    $query = $this->food::withTrashed()->where("id", $id);
                    if (!$this->hasPermission('food_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('food_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->restore();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Recovery success!'));
                break;
            case "clone":
                $this->checkPermission('food_create');
                foreach ($ids as $id) {
                    (new $this->food())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->food::where("id", $id);
                    if (!$this->hasPermission('food_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('food_update');
                    }
                    $row = $query->first();
                    $row->status = $action;
                    $row->save();
                    event(new UpdatedServiceEvent($row));
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }

    public function getForSelect2(Request $request)
    {
        $pre_selected = $request->query('pre_selected');
        $selected = $request->query('selected');
        if ($pre_selected && $selected) {
            if (is_array($selected)) {
                $items = $this->food::select('id', 'title as text')->whereIn('id', $selected)->take(50)->get();
            } else {
                $items = $this->food::find($selected);
            }
            return [
                'results'=>$items
            ];
        }
        $q = $request->query('q');
        $query = $this->food::select('id', 'title as text')->where("status", "publish");
        if ($q) {
            $query->where('title', 'like', '%' . $q . '%');
        }
        $res = $query->orderBy('id', 'desc')->limit(20)->get();
        return $this->sendSuccess([
            'results' => $res
        ]);
    }
}
